<a href="https://colab.research.google.com/github/Praveen3110/ML-zoomcamp-homework/blob/main/DATAZOOMCAMP_HOMEWORK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


Q1 PANDAS VERSION

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-29 15:34:31--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.2’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.05s   

2025-09-29 15:34:31 (18.0 MB/s) - ‘car_fuel_efficiency.csv.2’ saved [874188/874188]



In [ ]:
df=pd.read_csv("car_fuel_efficiency.csv")

In [ ]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

Q2 RECORD COUNT

In [ ]:
df.shape

(9704, 11)

Q3 FUEL TYPES

In [ ]:
df['fuel_type'].nunique()

2

Q4 MISSING VALUE

In [ ]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Q5 MAX FUEL EFFICIENCY

In [ ]:
df[df['origin']=="Asia"].fuel_efficiency_mpg.max()

23.759122836520497

Q6 MEDIAN VALUE OF HORSEPOWER

In [ ]:
df.horsepower.median() #old meadian value

149.0

In [ ]:
df["horsepower"]

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [ ]:
df["horsepower"].value_counts().head(1)

horsepower
152.0    142
Name: count, dtype: int64

In [ ]:
df["horsepower"].fillna(df["horsepower"].value_counts().idxmax(),inplace=True)

In [ ]:
df["horsepower"].median() #new meadian value

152.0

Q7 SUM OF WEIGHTS

In [ ]:
df.loc[df['origin']=="Asia",["vehicle_weight","model_year"]].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [ ]:
df1=df.loc[df['origin']=="Asia",["vehicle_weight","model_year"]].head(7)

In [ ]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [ ]:
x=df1[["vehicle_weight","model_year"]].values

In [ ]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [ ]:
XT=x.T #TRANSPOSE
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [ ]:
XTX=x.T @ x
XTX #MATRIX MATRIX MULTIPLATION

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [ ]:
XTX_invert=np.linalg.inv(XTX) #TAKING INVERSE FOR X
XTX_invert

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [ ]:
Y=[1100,1300,800,900,1000,1100,1200] #CREATING NEW COLUMN Y

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [ ]:
w= XTX_invert @ x.T @ Y
w

array([0.01386421, 0.5049067 ])

In [ ]:
total=w.sum() #sum of all the elements
total

np.float64(0.5187709081074016)